[package]
name = "au"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = "0.8.2"
proptest = "1.11.0"
serde_json = { version = "1.0.151", features = ["preserve_order"] }

[[bench]]
name = "au_bench"
harness = false

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
items_after_statements = "warn"
missing_const_for_fn = "warn"
redundant_else = "warn"
uninlined_format_args = "warn"
use_self = "warn"