[package]
name = "au"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
serde_json = { version = "1", features = ["preserve_order"] }
proptest = "1.11.0"
criterion = "0.8.2"

[[bench]]
name = "au_bench"
harness = false

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
missing_const_for_fn = "warn"
use_self = "warn"
uninlined_format_args = "warn"
redundant_else = "warn"
